AWSTemplateFormatVersion: "2010-09-09"

Resources:
  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "cron(0 0/12 ? * * *)"
      Name: woceventrule
      RoleArn: arn:aws:iam::765129888930:role/LabRole
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "LambdaFunction"
              - "arn:aws:lambda:us-east-1:765129888930:function:wordFetch"
          Id: "wordFetch"
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: wordFetch
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ScheduledRule"
          - "Arn"